name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # get commit hash id
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
      with:
        prefix: "commit-"

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:${{ steps.commit.outputs.short }} .

    - name: Docker image latest tagging
      run: docker tag ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:${{ steps.commit.outputs.short }} ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:latest
      
    - name: Docker-hub login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker-hub push w/ commit tag
      run: docker push ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:${{ steps.commit.outputs.short }}

    - name: Docker-hub push w/ latest tag
      run: docker push ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:latest
      
    - name: SSH remote command
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          sudo docker stop py-study-instagram
          sudo docker rm py-study-instagram
          sudo docker pull ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:${{ steps.commit.outputs.short }}
          sudo docker run --name py-study-instagram -p 8000:8000 -d ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:latest
