name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
      with:
        commit: "${{ github.event.workflow_run.head_sha }}"

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:${{ steps.commit.outputs.short }} .
      
    - name: Docker-hub login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker-hub push
      run: docker push ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:${{ steps.commit.outputs.short }}
      
    - name: SSH remote command
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          sudo docker stop py-study-instagram
          sudo docker rm py-study-instagram
          sudo docker pull ${{ secrets.DOCKERHUB_ID }}/py-study-instagram:${{ steps.commit.outputs.short }}
          sudo docker run --name py-study-instagram -p 8000:8000 -d jujihoon01/py-study-instagram:${{ steps.commit.outputs.short }}
